title = "Website Name"
baseURL = 'https://example.org'
languageCode = 'en-us'

[params]
	# "relatedtext" is the text that appears above the tag list at the bottom of pages.
	relatedtext = "Related"
	favicon = "/favicon.ico"

	# list items
	datesinlist = true
	authorsinlist = true

	# footer items
	nextprev = true
	taglist = true
	showrss = true

	custom_css = ["/css/syntax.css", "/css/style.css"]

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
		# enable using html in md files
			unsafe = true

	[markup.highlight]
		noClasses = true
		lineNos = true
		lineNumbersInTable = false
		anchorLineNos = false
		lineAnchors = ''
		style = "gruvbox"
		codeFences = true
		guessSyntax = false
		hl_Lines = ''
		hl_inline = false
		lineNoStart = 1
		noHl = false
		tabWidth = 8

## Top Menu Example
#[menu]
#	[[menu.main]]
#		Name = "Hossein"
#		URL = "/"
#		weight = 1
#
#	[[menu.main]]
#		Name = "RSS"
#		URL = "/index.xml"
#		weight = 2
#
#	[[menu.main]]
#		Name = "Tags"
#		URL = "/tags"
#		weight = 3
